- name: "Set user book lib dir to '{{ book_lib_dir }}' in '{{ calibre_user_prefs_file_path }}'"
  ansible.builtin.lineinfile:
    path: "{{ calibre_user_prefs_file_path }}"
    regexp: >-
      (^.*"library_path"): (.+)(,?)$
    line: >-
      \1: {{ book_lib_dir }}\3
    state: present
    create: false
    backrefs: true
  vars:
    quoted_dir: "\"{{ calibre_user_book_lib_dir }}\""
    book_lib_dir: "{{ calibre_user_book_lib_dir | ansible.builtin.ternary(quoted_dir, 'null') }}"
  become: true
  become_user: "{{ calibre_user_name }}"

