# - name: "Set GUI language to English in '{{ calibre_user_prefs_file_path }}'"
#   ansible.builtin.lineinfile:
#     path: "{{ calibre_user_prefs_file_path }}"
#     regexp: >-
#       (^.*"language"): (.+)(,?)$
#     line: >-
#       \1: "en"\3
#     create: false
#     backrefs: true
#   become: true
#   become_user: "{{ calibre_user_name }}"

# - name: "Set 'welcome_wizard_was_run' to 'true' in '{{ calibre_user_dynamic_settings_file_path }}'"
#   ansible.builtin.lineinfile:
#     path: "{{ calibre_user_dynamic_settings_file_path }}"
#     regexp: >-
#       (^.*"welcome_wizard_was_run"): (.+)(,?)$
#     line: >-
#       \1: true\3
#     create: false
#     backrefs: true
#   become: true
#   become_user: "{{ calibre_user_name }}"

# - name: "Set 'new_version_notification' to 'false' in '{{ calibre_user_gui_settings_file_path }}'"
#   ansible.builtin.lineinfile:
#     path: "{{ calibre_user_gui_settings_file_path }}"
#     regexp: >-
#       (^.*"new_version_notification"): (.+)(,?)$
#     line: >-
#       \1: false\3
#     create: false
#     backrefs: true
#   become: true
#   become_user: "{{ calibre_user_name }}"

