- name: "Define role-local vars for working with the DeDRM plugin collection"
  ansible.builtin.include_tasks: vars.yml

- name: "Download and extract the DeDRM plugin collection"
  ansible.builtin.include_tasks: download.yml

- name: "Enable all plugins in the DeDRM plugin collection"
  ansible.builtin.include_tasks: enable.yml
  when: calibre_enable_dedrm_plugin_collection

- name: "Disable all plugins in the DeDRM plugin collection"
  ansible.builtin.include_tasks: disable.yml
  when: not calibre_enable_dedrm_plugin_collection

