- name: "Copy skeleton '{{ calibre_dedrm_plugin_collection_settings_file_path }}', if not exist"
  ansible.builtin.template:
    dest: "{{ calibre_dedrm_plugin_collection_settings_file_path }}"
    src: "dedrm_json.j2"
    force: false
  become: true
  become_user: "{{ calibre_user_name }}"

- name: "Configure DeDRM plugin settings in '{{ calibre_dedrm_plugin_collection_settings_file_path }}'"
  ansible.builtin.lineinfile:
    path: "{{ calibre_dedrm_plugin_collection_settings_file_path }}"
    regexp: >-
      (^.*"serials"): (\[\n?.*\n?.*\])(,?)$
    line: >-
      \1: {{ serial_nums_array_string }}\3
    state: present
    create: false
    backrefs: true
  vars:
    serial_nums_fields: "{{ calibre_dedrm_plugin_kindle_serial_num_list | map(attribute='serial_num') }}"
    serial_nums_array_string: "{{ serial_nums_fields | list | ansible.builtin.to_json(indent=4) }}"
  become: true
  become_user: "{{ calibre_user_name }}"

