- name: "Copy skeleton '{{ calibre_dedrm_plugin_collection_settings_file_path }}', if not exist"
  ansible.builtin.template:
    dest: "{{ calibre_dedrm_plugin_collection_settings_file_path }}"
    src: "dedrm_json.j2"
    force: false
  become: true
  become_user: "{{ calibre_user_name }}"

- name: "Configure DeDRM plugin settings in '{{ calibre_dedrm_plugin_collection_settings_file_path }}'"
  ansible.builtin.replace:
    path: "{{ calibre_dedrm_plugin_collection_settings_file_path }}"
    regexp: >-
      (^.*"serials"): (\[\n?.*\n?.*\])(,?)$
    replace: >-
      \1: {{ serial_nums_array_string | indent(2) }}\3
  vars:
    serial_num_fields: "{{ calibre_dedrm_plugin_kindle_serial_num_list | map(attribute='serial_num') }}"
    serial_nums_array_string: "{{ serial_num_fields | list | to_nice_json }}"
  # Note: to_nice_json leaves ending ']' on last line unindented - could not fix
  changed_when: false
  become: true
  become_user: "{{ calibre_user_name }}"

