- name: "Run DeDRM plugin manually, to generate '{{ calibre_dedrm_plugin_collection_settings_file_path }}'"
  ansible.builtin.command:
    cmd: >-
      calibre-debug --run-plugin
      {{ calibre_dedrm_plugin_module_name | ansible.builtin.quote }}
  vars:
    search_str: "No plugin named {{ calibre_dedrm_plugin_module_name }} found"
  register: result
  failed_when: (search_str in result.stdout)
  creates: "{{ calibre_dedrm_plugin_collection_settings_file_path }}"
  become: true
  become_user: "{{ calibre_user_name }}"

- name: "Configure DeDRM plugin settings in '{{ calibre_dedrm_plugin_collection_settings_file_path }}'"
  ansible.builtin.lineinfile:
    path: "{{ calibre_dedrm_plugin_collection_settings_file_path }}"
    regexp: >-
      (^.*"serials"): (\[.*\])(,?)$
    line: >-
      \1: {{ serial_nums_array_string }}\3
    state: present
    create: false
    backrefs: true
  vars:
    serial_nums_fields: "{{ calibre_dedrm_plugin_kindle_serial_num_list | map(attribute='serial_num') }}"
    serial_nums_array_string: "{{ serial_nums_fields | list | to_json }}"
  become: true
  become_user: "{{ calibre_user_name }}"

