- name: "Define module names for plugins and plugin collections"
  ansible.builtin.set_fact:
    # DRM-handling for Kindle (azw/azw3), Adobe Adept, B&N, Mobipocket
    calibre_dedrm_plugin_module_name: "DeDRM"
    # DRM-handling for Kobo kepub
    calibre_obok_plugin_module_name: "Obok DeDRM"

- name: "Define base-names for plugins and plugin-collections"
  ansible.builtin.set_fact:
    calibre_dedrm_plugin_collection_base_name: "\
      {{ calibre_dedrm_plugin_module_name }}_tools_\
      {{ calibre_dedrm_plugin_collection.vers }}"

- name: "Define remote-URLs and local-dir-names for plugins and plugin collections"
  ansible.builtin.set_fact:
    calibre_dedrm_plugin_collection_remote_download_url: "\
      https://github.com/noDRM/DeDRM_tools/releases/download/\
      v{{ calibre_dedrm_plugin_collection.vers }}/\
      {{ calibre_dedrm_plugin_collection_base_name }}.zip"
    calibre_dedrm_plugin_collection_local_dir: "\
      {{ calibre_user_plugins_dir }}/{{ calibre_dedrm_plugin_collection_base_name }}"

- name: "Define local-zipfile-path and local-module-paths for plugins and plugin collections"
  ansible.builtin.set_fact:
    calibre_dedrm_plugin_collection_local_zipfile_path: "\
      {{ calibre_dedrm_plugin_collection_local_dir }}/{{ calibre_dedrm_plugin_collection_base_name }}.zip"
    calibre_dedrm_plugin_local_module_path: "\
      {{ calibre_dedrm_plugin_collection_local_dir }}/DeDRM_plugin.zip"
    calibre_obok_plugin_local_module_path: "\
      {{ calibre_dedrm_plugin_collection_local_dir }}/Obok_plugin.zip"

