- name: "Create user KFX Input plugin config dir at '{{ calibre_kfx_input_plugin_local_dir }}'"
  ansible.builtin.file:
    path: "{{ calibre_kfx_input_plugin_local_dir }}"
    state: directory
  become: true
  become_user: "{{ calibre_user_name }}"

- name: "Download KFX Input plugin from '{{ calibre_kfx_input_plugin_remote_download_url }}'"
  ansible.builtin.get_url:
    url: "{{ calibre_kfx_input_plugin_remote_download_url }}"
    dest: "{{ calibre_kfx_input_plugin_local_zipfile_path }}"
  become: true
  become_user: "{{ calibre_user_name }}"

- name: "Extract downloaded KFX Input plugin inside '{{ calibre_kfx_input_plugin_local_dir }}'"
  ansible.builtin.unarchive:
    src: "{{ calibre_kfx_input_plugin_local_zipfile_path }}"
    dest: "{{ calibre_kfx_input_plugin_local_dir }}"
    creates : "{{ calibre_kfx_input_plugin_local_module_path }}"
  become: true
  become_user: "{{ calibre_user_name }}"

