- name: "Define module names for plugins"
  ansible.builtin.set_fact:
    # DRM-handling for Kindle (kfx)
    calibre_kfx_input_plugin_module_name: "KFX Input"

- name: "Define base-names for plugins"
  ansible.builtin.set_fact:
    calibre_kfx_input_plugin_base_name: "\
      KFX_Input_plugin_\
      {{ calibre_kfx_input_plugin.vers }}"

- name: "Define remote-URLs and local-dir-names for plugins"
  ansible.builtin.set_fact:
    calibre_kfx_input_plugin_remote_download_url: "\
      https://plugins.calibre-ebook.com/\
      {{ calibre_kfx_input_plugin.url_id }}.zip"
    calibre_kfx_input_plugin_local_dir: "\
      {{ calibre_user_plugins_dir }}/{{ calibre_kfx_input_plugin_base_name }}"

- name: "Define local-zipfile-path and local-module-paths for plugins"
  ansible.builtin.set_fact:
    calibre_kfx_input_plugin_local_zipfile_path: "\
      {{ calibre_kfx_input_plugin_local_dir }}/{{ calibre_kfx_input_plugin_base_name }}.zip"
    calibre_kfx_input_plugin_local_module_path: "\
      {{ calibre_kfx_input_plugin_local_dir }}/KFX_plugin.zip"

